name: Deploy and Configure VMs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Generate Ansible Inventory
      run: ./ansible/inventory.sh

    - name: Set up Ansible
      uses: ansible/ansible-setup-action@v1

    - name: Run Ansible Playbook
      run: ansible-playbook -i ansible/inventory ansible/playbook.yml

