---
- hosts: all
  become: yes
  tasks:
    - name: Disable SELinux
      command: setenforce 0
      when: ansible_os_family == "RedHat"

    - name: Disable SELinux in config file
      replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=.*$'
        replace: 'SELINUX=disabled'
      when: ansible_os_family == "RedHat"

    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
      when: ansible_os_family == "RedHat"

- hosts: frontend
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Configure nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

- hosts: backend
  become: yes
  tasks:
    - name: Install Netdata
      apt:
        name: netdata
        state: present
      when: ansible_os_family == "Debian"

    - name: Start Netdata
      service:
        name: netdata
        state: started
        enabled: yes

