---
- name: Configure VMs
  hosts: all
  become: true
  vars:
    nginx_proxy_port: 19999

  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Stop and disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: false

- name: Configure frontend group
  hosts: frontend
  become: true
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Configure nginx proxy
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

- name: Configure backend group
  hosts: backend
  become: true
  tasks:
    - name: Install Netdata
      yum:
        name: netdata
        state: present

    - name: Start Netdata
      systemd:
        name: netdata
        state: started
        enabled: true

