name: Deploy VMs and Configure with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          
      - name: Initialize Terraform
        run: terraform init terraform/

      - name: Deploy infrastructure with Terraform
        run: terraform apply -auto-approve terraform/

      - name: Set up Python for Ansible
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies for Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Generate Ansible inventory
        run: ansible-playbook -i ansible/inventory.sh ansible/playbook.yml --tags "generate_inventory"

      - name: Configure VMs with Ansible
        run: ansible-playbook -i ansible/inventory.sh ansible/playbook.yml --skip-tags "generate_inventory"
        env:
          ANSIBLE_HOST_KEY_CHECKING: False

      - name: Clean up Terraform
        run: terraform destroy -auto-approve terraform/

